name: Update RSS Feed

on:
  schedule:
    # Run daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  update-rss:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install beautifulsoup4 requests
    
    - name: Generate RSS feed
      run: |
        python generate_author_rss_v2.py
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    
    - name: Commit updated RSS feed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add benjamin_delille_rss.xml
        git diff --staged --quiet || git commit -m "Update RSS feed - $(date)"
        git push
